version: 2
updates:
  # Configuration for Go modules
  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "daily"
    assignees:
      - "cheetahbyte"
    reviewers:
      - "cheetahbyte"
  
  # Configuration for npm (used by Svelte)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    assignees:
      - "cheetahbyte"
    reviewers:
      - "cheetahbyte"

  # Configuration for Docker
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
    assignees:
      - "cheetahbyte"
    reviewers:
      - "cheetahbyte"
