version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/server" 
    schedule:
      interval: "daily"
    assignees:
      - "cheetahbyte"
    reviewers:
      - "cheetahbyte"
    target-branch: "development"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    assignees:
      - "cheetahbyte"
    reviewers:
      - "cheetahbyte"
    target-branch: "development"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
    assignees:
      - "cheetahbyte"
    reviewers:
      - "cheetahbyte"
    target-branch: "development"
