
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: database
      POSTGRES_HOST_AUTH_METHOD: trust  # This allows passwordless access
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin  # You can set this to an empty string, but it's not recommended
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: