services:
  db:
    image: postgres:alpine
    container_name: keinbudget-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keinbudget
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d keinbudget"]
      interval: 5s
      timeout: 3s
      retries: 5

  valkey:
    image: valkey/valkey:7
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: unless-stopped

volumes:
  pgdata:
  valkey_data:
