// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO credentials (
  id, user_id, public_key, sign_count, transports
)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCredentialParams struct {
	ID         string
	UserID     uuid.UUID
	PublicKey  []byte
	SignCount  int64
	Transports []string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.PublicKey,
		arg.SignCount,
		pq.Array(arg.Transports),
	)
	return err
}

const getCredentialsByUserID = `-- name: GetCredentialsByUserID :many
SELECT id, user_id, public_key, sign_count, transports, created_at FROM credentials WHERE user_id = $1
`

func (q *Queries) GetCredentialsByUserID(ctx context.Context, userID uuid.UUID) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.SignCount,
			pq.Array(&i.Transports),
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
