// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Credential struct {
	ID         string
	UserID     uuid.UUID
	PublicKey  []byte
	SignCount  int64
	Transports []string
	CreatedAt  sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Username  string
	CreatedAt sql.NullTime
}

type Wallet struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	StartBalance string
	Icon         sql.NullString
}
