name: Frontend Lint & Test

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
      - development
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - main
      - development

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Check with Biome
        continue-on-error: true
        run: npx biome check .