name: Playwright Tests
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - 'main'
      - 'development'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Determine image tag
      id: tag
      run: |
        if [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
          echo "tag=latest" >> "$GITHUB_OUTPUT"
        elif [[ "${{ github.event.workflow_run.head_branch }}" == "development" ]]; then
          echo "tag=nightly" >> "$GITHUB_OUTPUT"
        else
          echo "tag=dev" >> "$GITHUB_OUTPUT"
        fi
    - name: Show tag used
      run: |
        echo "Using tag image ${{steps.tag.outputs.tag}}"
    - name: Pull Docker image
      run: docker pull ghcr.io/cheetahbyte/keinbudget:${{ steps.tag.outputs.tag }}
    - name: Run Docker container
      run: docker run -d -p 8000:8000 --name keinbudget ghcr.io/cheetahbyte/keinbudget:${{ steps.tag.outputs.tag }}
    - name: Install dependencies
      working-directory: client
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: client
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: client
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
