name: Python Testing
permissions:
  contents: read

on:
  push:
    paths:
      - "server/**"
    branches:
      - main
      - development
  pull_request:
    paths:
      - "server/**"
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | bash

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Add uv to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Define a cache dependency glob
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "server/uv.lock"

      - name: Install dependencies with uv (incl. dev)
        run: |
          cd server
          uv sync --locked --all-extras --dev

      - name: Run tests with coverage
        run: |
          cd server
          uv run pytest --cov=server --cov-report=term --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: server/coverage.xml

      - name: Lint with Ruff
        run: |
          cd server
          uv run ruff check .
