name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Navigate to server directory
      run: cd server

    - name: Install dependencies
      run: go mod download
      working-directory: ./server

    - name: Run tests
      run: go test ./...
      working-directory: ./server